/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.of.code

import java.io.File

fun main() {
    val resource = ClassLoader.getSystemClassLoader().getResource("input1.txt")
    val readLines = File(resource.path).readLines()
    println("Hello ${readLines.size}")
}
